version: "3"

networks:
  loki:

volumes:
  grafana-data:
  grafana-logs:

services:
  loki:
    image: grafana/loki:2.4.2
    hostname: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    build:
      context: promtail
    hostname: promtail
    volumes:
      - /var/log:/var/log
      - grafana-logs:/var/log/grafana
    command: -config.file=/etc/promtail/local-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana-oss:8.2.6
    hostname: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_LOG_MODE: "console file"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
    networks:
      - loki
